POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphbmVkb2VAZG9tYWluLmNvbSIsImlkIjoxLCJpYXQiOjE2Mzg3NDE1ODd9.3HOs2Z2ZyJzzxXQSzNzbW5bAuLUhl5pGeoCyrKMcGkk

{
  "author": "Jane Doe",
  "url": "https://anotherexampleblog.com/post-1567",
  "title": "A blog title that is very long",
  "likes": 4568,
  "year": "2000"
}