DELETE http://localhost:3001/api/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphbmVkb2VAZG9tYWluLmNvbSIsImlkIjoyLCJpYXQiOjE2Mzg3OTgxMzl9.Kyz1VWb8QPlx17_E81LgBr_3RKiSuc5T9DAZSLYsE2o