PUT http://localhost:3001/api/readinglists/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphbmVkb2VAZG9tYWluLmNvbSIsImlkIjoxLCJpYXQiOjE2Mzg3ODg5MzB9.OtnH4T17VlZQ-_5ZwCLNlYTUd8_da1Ouf0V0CKPZ3i8

{
  "read": true
}